reloj creado
RSKY18141051/Proyecto-Tamag-KLMOF pull request #28
Opened 2023-10-06 22:46 UTC by RSKY18141051

#5 
se creo la aplicación de reloj

2023-10-06 23:38 UTC, alx3416 commented on reloj.py
> +    canvas.create_text(150 + 120 * math.cos(angle) * 0.8, 150 - 120 * math.sin(angle) * 0.8, text=str(i + 1), fill="black")
```suggestion
    canvas.create_text(150 + 120 * math.cos(angle) * 0.8, 150 - 120 * math.sin(angle) * 0.8, text=str(i + 1), fill="black", font=('Helvetica','6','bold'))
```

2023-10-06 23:41 UTC, alx3416 requested changes
El minutero del reloj va en sentido contrario, solo es cuestión de ajustar el ciclo for y la variable de iteración

Añado sugerencia para personalizar el tipo de fuente y su tamaño para que sean mas legibles los números mostrados
![image](https://github.com/RSKY18141051/Proyecto-Tamag-KLMOF/assets/63263335/cf1c11c7-62e8-4bb0-a97a-c96547320b6f)

2023-10-09 19:41 UTC, FidelXXl commented
Cambiar a digital o crear la funcionalidad para alternar entre ellos

2023-10-13 22:41 UTC, alx3416 approved these changes
Good work!
![image](https://github.com/RSKY18141051/Proyecto-Tamag-KLMOF/assets/63263335/3bbb7402-1b17-4180-bbad-3af5a600b769)

2023-10-20 22:28 UTC, alx3416 approved these changes

2023-10-24 23:01 UTC, closed without merging

2023-10-26 08:00 UTC, alx3416 commented
Se decidió remover el reloj completamente? ya que decidieron cerrar el PR en lugar de hacer merge con el branch principal